export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const FETCH_DATA_VIEW_REQUEST = " FETCH_DATA_VIEW_REQUEST";
export const FETCH_DATA_VIEW_SUCCESS = "FETCH_DATA_VIEW_SUCCESS";
export const FETCH_DATA_VIEW_FAILURE = "FETCH_DATA_VIEW_FAILURE";
export const FETCH_DATA_VIEW_ERROR = "FETCH_DATA_VIEW_ERROR";

export const EDIT_FIELD = "EDIT_FIELD";
export const SAVE_FIELD_REQUEST = "SAVE_FIELD_REQUEST";
export const SAVE_FIELD_SUCCESS = "SAVE_FIELD_SUCCESS";
export const SAVE_FIELD_FAILURE = "SAVE_FIELD_FAILURE";

export const NOTES_FETCH_REQUEST = "NOTES_FETCH_REQUEST";
export const NOTES_FETCH_SUCCESS = "NOTES_FETCH_SUCCESS";
export const NOTES_FETCH_FAILURE = "NOTES_FETCH_FAILURE";

export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_ERROR = "ADD_NOTE_ERROR";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_ERROR = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";

export const REMOVE_NOTE_REQUEST = "REMOVE_NOTE_REQUEST";
export const REMOVE_NOTE_ERROR = "REMOVE_NOTE_REQUEST";
export const REMOVE_NOTE_SUCCESS = "REMOVE_NOTE_SUCCESS";

export const SENT_MAIL_REQUEST = "SENT_MAIL_REQUEST";
export const SENT_MAIL_SUCCESS = "SENT_MAIL_SUCCESS";
export const SENT_MAIL_ERROR = "SENT_MAIL_ERROR";

export const FETCH_REF_REQUEST = "FETCH_REF_REQUEST";
export const FETCH_REF_SUCCESS = "FETCH_REF_SUCCESS";
export const FETCH_REF_FAILURE = "FETCH_REF_FAILURE";
